### ISSUE TITLE
Cannot Set Rules Against Integers

### ISSUE THREAD

**Issue by webmd-lsetch** [Sage-Bionetworks/Bridge-iOS-SDK#117]
In Survey, created an integer question. Added two rules. Rule 1 = 2 and skips to question further along.
Rule 1 = 1 and goes to the next question. 

I have tried adjusting the max to limit the options to 2.

**Comment by Erin-Mounts** [comment]
Sorry, I'm not following the problem description here. Can you clarify what it is you're trying to do and what you're expecting to happen that isn't happening (or what is happening that you weren't expecting)?

Also Bridge-iOS-SDK only retrieves and caches the Surveys (and any attached rules) from Bridge and passes them along to BridgeAppSDK as iOS objects, which is where any interpretation of those rules would happen, so that might be a more appropriate framework for this issue, if I'm understanding it at all.

**Comment by webmd-lsetch** [comment]
In the Health History Survey I created an integer question. I applied two rules to the question. The rules are not working when I take the survey. The question is related to how many x you are carrying.  I have tried multiple rule configurations for this question as an integer question. None of them are working.

**Comment by Erin-Mounts** [comment]
Ah, OK. As I mentioned, actually applying rules while taking a survey is in the purview of BridgeAppSDK. Can you please add this issue there and close it here?
